### ISSUE TITLE
HttpContext.Current.User is null

### ISSUE THREAD

**Issue by jimarnold** [jennifersmith/plasma#21]
Trying to test an app that relies on this property. Have tried to investigate and hack in a solution but no luck so far.

**Comment by davidwhitney** [comment]
In a little bit of thread necromancy - I'm spending a little bit of time pushing code in this around today, and I appreciate that this is ancient in internet time, but this seems to be an invalid bug report.

I've written a test that verifies HttpContext.Current.User exists in the default sample app - so I'd recommend this issue is closed. Let me know if you remember ever getting anywhere with this.
